services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.5-alpine
    container_name: ch-dev
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: demo
      CLICKHOUSE_USER: demo
      CLICKHOUSE_PASSWORD: demo
    ulimits:
      nofile:
        soft: 262144
        hard: 262144